version: '3'

services:
  jira:
    depends_on:
      - mysql
    container_name: jira
    restart: "no"
    image: cptactionhank/atlassian-jira-software:7.13.0
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
      - LETSENCRYPT_EMAIL=admin@jira.example.com
    deploy:
      resources:
        limits:
          cpus: '1.001'
          memory: 1G
        reservations:
          cpus: '1.0001'
          memory: 2G
    ports:
      - '8080:8080'
    volumes:
      - ./jira-data:/var/atlassian/jira  # JIRA_HOME
      - ./dbconfig.xml:/var/atlassian/jira/dbconfig.xml
      - ./var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      jira-network:

  mysql:
    container_name: mysql
    restart: "no"
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=jiradb          # this database will be created on image startup
      - MYSQL_USER=jiradbuser               # this user will be granted superuser permissions on MYSQL_DATABASE
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_HOST=% 
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      jira-network:

networks:
  jira-network:
    driver: bridge

volumes:
  jira-data:
  mysql-data:
